# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(svg|csv)$'
      - id: end-of-file-fixer
        exclude: '\.(svg|csv)$'
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        name: Backend Ruff Lint
        args: [ --fix ]
      - id: ruff-format
        name: Backend Ruff Format

  - repo: local
    hooks:
      - id: pyright
        name: Backend Pyright
        entry: bash -c 'cd backend && uv run pyright'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
